name: Test

on:
  push:
  pull_request:
    branches:
    - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Deno environment
      uses: denolib/setup-deno@v2.1.0
      with:
        deno-version: v1.x

    - name: Run deno test
      run: |
        deno --version
        deno cache deps.ts
        deno test --allow-read --allow-net --allow-env
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
